[package]
name = "clarinet"
version = "0.5.4"
authors = ["Ludo Galabru <ludovic@galabru.com>"]
edition = "2018"
description = "Clarinet is a clarity runtime packaged as a command line tool, designed to facilitate smart contract understanding, development, testing and deployment."
readme = "README.md"
license = "GPL-3.0-only"
keywords = ["blockstack", "blockchain", "clarity", "smart-contract", "repl"]
exclude = ["examples/**"]
homepage = "https://github.com/lgalabru/clarinet"
repository = "https://github.com/lgalabru/clarinet"
categories = ["command-line-utilities", "development-tools", "development-tools::build-utils"]

[workspace]
members = [".", "xtask/"]

[build-dependencies]
deno_core = "=0.80.2"
deno_runtime = "=0.9.3"
# deno_web = "=0.31.0"
regex = "1.4.3"
serde = { version = "1.0.123", features = ["derive"] }

[target.'cfg(windows)'.build-dependencies]
winapi = "0.3.9"
winres = "0.1.11"

[dependencies]
clap = { version = "3.0.0-beta.2" }
toml = { version = "0.5.6", features = ["preserve_order"] }
serde = "1"
serde_derive = "1"
deno_core = "=0.80.2"
deno_runtime = "=0.9.3"
# deno_web = "=0.31.0"
rusty_v8 = "=0.20.0"
# clarity_repl = { package = "clarity-repl", path = "../../clarity-repl", features = ["cli"] }
clarity_repl = { package = "clarity-repl", version = "0.7.4" }
bip39 = "1.0.0-rc1"
aes = "0.6.0"
base64 = "0.13.0"
block-modes = "0.7.0"
bs58 = "0.4.0"
rand = "0.8.3"
ring = "0.16.20"
ripemd160 = "0.9.1"
libsecp256k1 = "0.3.5"
sha2 = "0.9.3"
uuid = { version = "0.8.2", features = ["v4"] }
hmac = "0.10.1"
pbkdf2 = { version = "0.7.3", features=["parallel"], default-features = false }
hex = "0.4.3"
futures = "0.3.12"
tokio = { version = "1.2.0", features = ["full"] }
lazy_static = "1.4.0"
atty = "0.2.14"
jsonc-parser = "0.15.1"
notify = "=5.0.0-pre.4"
sourcemap = "6.0.1"
swc_bundler = "0.25.1"
swc_common = { version = "0.10.12", features = ["sourcemap"] }
swc_ecmascript = { version = "0.24.1", features = ["codegen", "dep_graph", "parser", "proposal", "react", "transforms", "typescript", "visit"] }
tempfile = "3.2.0"
termcolor = "1.1.2"
text-size = "1.1.0"
walkdir = "2.3.1"
regex = "1.4.3"
libc = "0.2.86"
encoding_rs = "0.8.28"
percent-encoding = "2.1.0"
pin-project = "1.0.5"
indexmap = { version = "1.6.1", features = ["serde"] }
shell-escape = "0.1.5"
tiny-hderive = "0.3.0"
reqwest = { version = "0.11", features = ["json"] }

[target.'cfg(windows)'.dependencies]
fwdansi = "1.1.0"
winapi = { version = "0.3.9", features = ["knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }

[package.metadata.winres]
OriginalFilename = "clarinet.exe"
LegalCopyright = ""
ProductName = "Clarinet"
FileDescription = ""
